### PR TITLE
Fix: Workflow Identity

### LINKED ISSUE #92: Workflow identity
Transact supports identifying workflows and RBAC through `authenticated_user` and `authenticated_roles`.

This can be done by adding a few functional options to `RunWorkflow` and `EnqueueWorkflow`:
- `WithAuthenticatedUser`
- `WithAuthenticatedRoles`
- `WithAssumedRole`

### PR DESCRIPTION
**Pull request by vr-varad**
Fixes #92

### CODE REVIEW

File: dbos/system_database.go [hunk 1]
```diff
@@ -489,7 +490,7 @@ func (s *sysDB) insertWorkflowStatus(ctx context.Context, input insertWorkflowSt
 		input.status.QueueName,
 		input.status.AuthenticatedUser,
 		input.status.AssumedRole,
-		input.status.AuthenticatedRoles,
+		pgtype.Array[string]{Elements: input.status.AuthenticatedRoles},
```
Comment (vr-varad) [inline dbos/system_database.go]: As the authenticated roles is an array of string, I was getting this error for the news tests
```
failed to insert workflow status: failed to encode args[6]: unable to encode []string{"reader", "writer"} into text format for text (OID 25): cannot find encode plan
```
But then added this to allow inserting array, which is giving bunch of error, i tried but coudn't get another way.
What are your thoughts?

Comment (vr-varad) [reply dbos/system_database.go]: @maxdml @kraftp

Comment (maxdml) [reply dbos/system_database.go]: The reason you are having this issue is that `authenticated_roles` is represented as a single `TEXT` column in Postgres. To match the other DBOS implementations, we should marshal `input.status.AuthenticatedRoles` to JSON and insert that in the database. On the read path, we should unmarshal it.

File: dbos/system_database.go [hunk 2]
```diff
@@ -483,14 +483,18 @@ func (s *sysDB) insertWorkflowStatus(ctx context.Context, input insertWorkflowSt
 	var result insertWorkflowResult
 	var timeoutMSResult *int64
 	var workflowDeadlineEpochMS *int64
+
+	// Marshal authenticated roles (slice of strings) to JSON for TEXT column
+	authenticatedRoles, _ := json.Marshal(input.status.AuthenticatedRoles)
```
Comment (maxdml) [inline dbos/system_database.go]: Please handle errors explicitly

**Review by maxdml — APPROVED** [review]
lgtm, thanks @vr-varad
