### PR TITLE
Fix: Handle max retries in awaitWorkflowResult

### LINKED ISSUE #143: Handle max retries in awaitWorkflowResult
Right now we only handle success, error, and cancel.

Max retry should be similar to success/error

### PR DESCRIPTION
**Pull request by vr-varad**
Fixes #143

### CODE REVIEW

File: dbos/queues_test.go [hunk 1]
```diff
@@ -366,9 +366,17 @@ func TestWorkflowQueues(t *testing.T) {
 		// Check the workflow completes
 		dlqCompleteEvent.Set()
 		for _, handle := range handles {
-			result, err := handle.GetResult()
-			require.NoError(t, err, "failed to get result from recovered workflow handle")
-			assert.Equal(t, "test-input", result, "expected result to be 'test-input'")
+			result, _ := handle.GetResult()
```
Comment (vr-varad) [inline dbos/queues_test.go]: @maxdml I made changes in the test, but I am not sure how to handle result err.

Comment (maxdml) [reply dbos/queues_test.go]: You have to type assert it into a `DBOSError` and then you can check it's `Is` method with the new error code.

We don't care about the result, we're just interested in checking the error. All the handles should return an error.

**Comment by vr-varad** [comment]
But if we look at the failing tests, not all handles are returning an error. // @maxdml 
(https://github.com/dbos-inc/dbos-transact-golang/actions/runs/19861284355/job/56911788635?pr=190#step:11:2082)

File: dbos/queues_test.go [hunk 2]
```diff
@@ -365,12 +365,16 @@ func TestWorkflowQueues(t *testing.T) {
...
-			result, err := handle.GetResult()
-			require.NoError(t, err, "failed to get result from recovered workflow handle")
-			assert.Equal(t, "test-input", result, "expected result to be 'test-input'")
+
+			_, resultErr := handle.GetResult()
+
+			var dbosErr *DBOSError
+			require.ErrorAs(t, resultErr, &dbosErr, "expected error to be of type *DBOSError, got %T", resultErr)
+
+			assert.Equal(t, DBOSErrorCode(13), dbosErr.Code, "expected workflow to be in DLQ after max retries exceeded")
```
Comment (maxdml) [inline dbos/queues_test.go]: Can you use the constant `MaxStepRetriesExceeded` instead of hardcoding the number please? 🙏

**Comment by maxdml** [comment]
> I have made the required changes, kindly review // @maxdml Not aware of why the security checks are failing, is it related to go version?

vuln check are fixed now (I rebased your branch on top of main)

**Comment by vr-varad** [comment]
Made the changes // @maxdml
