### PR TITLE
Fix: Accept custom pgxpool

### LINKED ISSUE #87: Accept custom pgxpool
Accept user-provided pgxpool objects to configure the system database

### PR DESCRIPTION
**Pull request by vr-varad**
Fixes #87

### CODE REVIEW

File: dbos/system_database.go [hunk 1]
```diff
@@ -229,7 +229,7 @@ func runMigrations(databaseURL string) error {
 }
 
 // New creates a new SystemDatabase instance and runs migrations
-func newSystemDatabase(ctx context.Context, databaseURL string, logger *slog.Logger) (systemDatabase, error) {
+func newSystemDatabase(ctx context.Context, databaseURL string, custom_pool *pgxpool.Pool, logger *slog.Logger) (systemDatabase, error) {
```
Comment (maxdml) [inline dbos/system_database.go]: Here, let's create a new input structure for `newSystemDatabase`. It is a good practice to have input strucs when a function takes more than two arguments, context excluded. The struct would look like

```golang
type newSystemDatabaseInput struct {
    databaseURL string
    pgxpool *pgxpool.Pool
    logger *slog.Logger
}
```

And the signature of  becomes

```golang
func newSystemDatabase(ctx context.Context, input ) (systemDatabase, error) {
```

File: dbos/dbos.go [hunk 2]
```diff
@@ -42,6 +43,7 @@ type Config struct {
 	ApplicationVersion string          // Application version (optional, overridden by DBOS__APPVERSION env var)
 	ExecutorID         string          // Executor ID (optional, overridden by DBOS__VMID env var)
 	Context            context.Context // User Context
+	Pool               *pgxpool.Pool   // Custom Pool
```
Comment (maxdml) [inline dbos/dbos.go]: Let's call this `SystemDBPool` for clarity (DBOS users are familiar with the concept of a "system" database)

File: dbos/dbos.go [hunk 3]
```diff
@@ -325,8 +328,14 @@ func NewDBOSContext(ctx context.Context, inputConfig Config) (DBOSContext, error
 
 	initExecutor.applicationID = os.Getenv("DBOS__APPID")
 
+	newSystemDatabaseInputs := newSystemDatabaseInput{
+		databaseURL: config.DatabaseURL,
+		custom_pool: config.Pool,
```
Comment (maxdml) [inline dbos/dbos.go]: nit: let's call this `customPool` to be consistent with the rest of the code (here and in the  constructor bellow)

File: dbos/dbos_test.go [hunk 4]
```diff
@@ -58,6 +61,54 @@ func TestConfig(t *testing.T) {
...
+		// Logger
+		var buf bytes.Buffer
+		slogLogger := slog.New(slog.NewTextHandler(&buf, &slog.HandlerOptions{
+			Level: slog.LevelDebug,
+		}))
+
+		slogLogger = slogLogger.With("service", "dbos-test", "environment", "test")
+
+		// Custom Pool
+		poolConfig, _ := pgxpool.ParseConfig(databaseURL)
```
Comment (maxdml) [inline dbos/dbos_test.go]: Check errors here with `require.NoError(t, err)`

File: dbos/dbos_test.go [hunk 5]
```diff
@@ -58,6 +61,54 @@ func TestConfig(t *testing.T) {
...
+		require.NotNil(t, customdbosContext)
+
+		dbosCtx, ok := customdbosContext.(*dbosContext)
+		require.True(t, ok)
+		sysDB, ok := dbosCtx.systemDB.(*sysDB)
+		require.True(t, ok)
+		assert.Same(t, pool, sysDB.pool, "The pool in dbosContext should be the same as the custom pool provided")
+
+		stats := sysDB.pool.Stat()
+		assert.Equal(t, int32(10), stats.MaxConns(), "MaxConns should match custom pool config")
```
Comment (maxdml) [inline dbos/dbos_test.go:108]: Let's do a full config check using https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#Pool.Config

File: dbos/system_database.go [hunk 6]
```diff
@@ -241,24 +252,37 @@ func newSystemDatabase(ctx context.Context, databaseURL string, logger *slog.Log
...
+
+		// Add acquire timeout to prevent indefinite blocking
+		config.ConnConfig.ConnectTimeout = 10 * time.Second
+
+		// Create pool with configuration
+		new_pool, err := pgxpool.NewWithConfig(ctx, config)
+		if err != nil {
+			return nil, fmt.Errorf("failed to create connection pool: %v", err)
+		}
+		pool = new_pool
```
Comment (maxdml) [inline dbos/system_database.go]: `newPool`

File: dbos/dbos_test.go [hunk 7]
```diff
@@ -58,6 +61,62 @@ func TestConfig(t *testing.T) {
...
+		sysdbConfig := sysDB.pool.Config()
+		assert.Equal(t, int32(10), sysdbConfig.MaxConns)
+		assert.Equal(t, int32(5), sysdbConfig.MinConns)
+		assert.Equal(t, 2*time.Hour, sysdbConfig.MaxConnLifetime)
+		assert.Equal(t, 2*time.Minute, sysdbConfig.MaxConnIdleTime)
+		assert.Equal(t, 10*time.Second, sysdbConfig.ConnConfig.ConnectTimeout)
+
+		customdbosContext.Shutdown(1 * time.Minute)
+		err = pool.Ping(context.Background())
+		assert.NoError(t, err, "Custom pool should not be closed by Shutdown and should still be usable")
```
Comment (maxdml) [inline dbos/dbos_test.go]: DBOS will close the custom pool for the user by design. Simpler that way.

Comment (vr-varad) [reply dbos/dbos_test.go]: So should I remove this check? @maxdml

Comment (maxdml) [reply dbos/dbos_test.go]: > So should I remove this check? @maxdml

Yup, not needed -- DBOS will shutdown the pool when the DBOS context is shut down.

**Comment by vr-varad** [comment]
Done!! @maxdml 
and test passed as well!!!
image

File: dbos/dbos_test.go [hunk 8]
```diff
@@ -58,6 +61,58 @@ func TestConfig(t *testing.T) {
...
+			Logger:       slogLogger,
+			SystemDBPool: pool,
+		}
+
+		customdbosContext, err := NewDBOSContext(context.Background(), config)
+		require.NoError(t, err)
+		require.NotNil(t, customdbosContext)
+
+		dbosCtx, ok := customdbosContext.(*dbosContext)
+		require.True(t, ok)
```
Comment (maxdml) [inline dbos/dbos_test.go:101]: You need to defer the shutdown of the DBOS context, that's why the tests are failing

```go
defer dbosCtx.Shutdown(10 * time.Second)
```
